title: 'Mushrooms '
description: 'I will grow magical mushrooms '
template:
  repo: mushrooms-template
  name: mushrooms
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
